GitLab API / bb8 gitlab compat
T4D-Suites/Tools4Dev pull request #18
Opened 2021-09-21 12:37 UTC by tk463

Base implem for gitlab api (tested with v12.10)
Lots of duplicate files on bb8 to be able to switch between bitbucket and gitlab

2021-09-22 08:26 UTC, QuentinNIO requested changes

2021-09-22 08:31 UTC, tk463 commented on Modules/bb8/_main_.env
> +case $bb8Mode in
Can you add the value in T4D Team Default ?

2021-09-27 10:20 UTC, QuentinNIO requested changes

2021-09-27 10:20 UTC, QuentinNIO commented on Modules/bb8/_main_.env
> +case $T4D_BB8_MODE in
Please add Default value in Modules/bb8/_main_.env 

before bb8() definition
`T4D_BB8_MODE="${T4D_BB8_MODE:-bitbucket}"`

2021-09-27 10:26 UTC, QuentinNIO approved these changes

2021-09-29 10:19 UTC, merged